Add accounting list
fastmonkeys/netvisor.py pull request #7
Opened 2016-09-05 13:36 UTC by tvuotila

Refs fastmonkeys/netvisor.py#6

I made a couple of choices: Let's say that `accounting = netvisor.accounting.list()`.
 - `accounting` is always a list.
 - `accounting[i]['lines']` is always a list. (Provided that index "i" exist.)
 - `accounting[i]['lines'][j]['dimensions']` is always a list. (Provided that indexes "i" and "j" exist.)
 - I shortened many names like `voucher_date` -> `date`, `netvisor_key` -> `key`.
 - Fields like `date = FinnishDate(load_from='voucher_date')` could have been written as `voucher_date = FinnishDate(attribute='date')`

2016-09-05 13:49 UTC, tvuotila commented
This time, I tested the code with production data.

2016-09-08 06:40 UTC, tvuotila commented
Marshmallow 2.10.0 introduced [a bug](https://github.com/marshmallow-code/marshmallow/issues/521) which crashes tests.

2016-09-14 11:27 UTC, tvuotila commented
Tests also fail because of marshmallow-code/marshmallow#528

2016-09-15 03:42 UTC, sloria commented
Thank you @tvuotila for the patches! They are now released in marshmallow 2.10.1

2016-09-15 05:27 UTC, tvuotila commented
@jpvanhal This is now green. Can you take a look?

2016-09-16 07:10 UTC, jpvanhal commented on netvisor/requests/accounting.py
> +    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Match the underline length with the text above.

2016-09-16 07:10 UTC, jpvanhal commented on netvisor/responses/accounting.py
> +    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Match the underline length with the text above.

2016-09-16 07:11 UTC, jpvanhal commented on netvisor/schemas/accounting/list.py
> +    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Match the underline length with the text above.

2016-09-16 07:12 UTC, jpvanhal commented on netvisor/services/accounting.py
> +    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Match the underline length with the text above.

2016-09-16 07:14 UTC, jpvanhal commented on netvisor/services/accounting.py
> +        return date.strftime('%Y-%m-%d')
`date.isoformat()` does the same thing, but it's a bit cleaner

2016-09-16 07:18 UTC, jpvanhal commented on netvisor/services/accounting.py
> +            camelize(key): format_dates(value)
I would prefer a more explicit approach. You cannot see what query parameters there are without going to Netvisor's documention.

2016-09-16 07:18 UTC, jpvanhal commented on netvisor/services/accounting.py
> +    except AttributeError:
I don't really like that this function is called for values other than dates.

2016-09-16 07:19 UTC, jpvanhal commented on tests/services/test_accounting.py
> +class TestAccountingService(object):
Add a test for the query parameters.

2016-09-16 07:22 UTC, jpvanhal requested changes
Overall looks good! 

Just a couple formatting issues in the docstrings, and I'd like some changes to the query parameters handling plus tests for them.

Also, I think the marshmallow requirement must be updated, if this PR depends on some recent bug fixes.

2016-09-16 10:20 UTC, tvuotila commented
@jpvanhal Fixed.

Requirement update is its own commit, because it is not related the change. The incompatible feature is the one tested by `test_create_with_unknown_fields` test methods.

2016-09-19 14:28 UTC, jpvanhal approved these changes

2016-09-19 14:28 UTC, merged